/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     HX711
  * - <b>Project file</b>:     G:/ti/workspace_v8/scs/nortos/HX711/HX711.scp
  * - <b>Code prefix</b>:      HX711
  * - <b>Operating system</b>: None
  * - <b>Tool version</b>:     2.2.0.569
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC2640R2F, revision -, package QFN32 4x4 RSM
  * - <b>Created</b>:          2018-08-23 06:09:41.659
  * - <b>Computer</b>:         DESKTOP-NJ22OJR
  * - <b>User</b>:             W
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * HX711 24bit ADC driver
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - ADC24bit:
  *     - <b>AXS: VCC</b>: DIO9
  *     - <b>I: DT</b>: DIO0
  *     - <b>O: SCK</b>: DIO8
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_adc24bit ADC24bit
  * No description entered
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     HX711
  * - <b>Code prefix</b>:      HX711
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_HX711_H
#define SCIF_HX711_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_none.h"


/// Target chip name
#define SCIF_HX711_TARGET_CHIP_NAME_CC2640R2F
/// Target chip package
#define SCIF_HX711_TARGET_CHIP_PACKAGE_QFN32_4X4_RSM

/// Number of tasks implemented by this driver
#define SCIF_HX711_TASK_COUNT 1

/// ADC24bit: Task ID
#define SCIF_HX711_ADC24BIT_TASK_ID 0


/// ADC24bit I/O mapping: VCC
#define SCIF_HX711_ADC24BIT_DIO_AXS_VCC 9
/// ADC24bit I/O mapping: DT
#define SCIF_HX711_ADC24BIT_DIO_I_DT 0
/// ADC24bit I/O mapping: SCK
#define SCIF_HX711_ADC24BIT_DIO_O_SCK 8


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// ADC24bit: Task configuration structure
typedef struct {
    uint16_t adcDthr; ///< 
    uint16_t bCount;  ///< 
    uint16_t dCount;  ///< adc sample block size
} SCIF_HX711_ADC24BIT_CFG_T;


/// ADC24bit: Task output data structure
typedef struct {
    int16_t  adcD;   ///< 
    int16_t  adcVal; ///< 
    uint16_t buzz;   ///< 
} SCIF_HX711_ADC24BIT_OUTPUT_T;


/// ADC24bit: Task state structure
typedef struct {
    int16_t  adcVal; ///< 
    uint16_t bCount; ///< 
    uint16_t buzz;   ///< 
    uint16_t dCount; ///< ADC samples have collected in the current block
    uint16_t exit;   ///< Set to exit the ADC data colletion
} SCIF_HX711_ADC24BIT_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_HX711_ADC24BIT_CFG_T cfg;
        SCIF_HX711_ADC24BIT_OUTPUT_T output;
        SCIF_HX711_ADC24BIT_STATE_T state;
    } adc24bit;
} SCIF_HX711_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifHx711TaskData    (*((volatile SCIF_HX711_TASK_DATA_T*) 0x400E00EA))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifHx711DriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifHx711ReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifHx711StartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifHx711StartRtcTicksNow(uint32_t tickPeriod);
void scifHx711StopRtcTicks(void);


#endif
//@}


// Generated by DESKTOP-NJ22OJR at 2018-08-23 06:09:41.659
